apiVersion: apps/v1
kind: Deployment
metadata:
  name: flatboat-operator
spec:
  selector:
    matchLabels:
      app: flatboat-operator
  template:
    metadata:
      labels:
        app: flatboat-operator
    spec:
      containers:
      - name: flatboat-operator
        image: juancsucoder/flatboat-operator:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
