apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flatboatworkloads.flatboat.juancsu.coder
spec:
  group: flatboat.juancsu.coder
  versions:
  - name: v6
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              launch:
                type: object
                properties:
                  package:
                    type: string
                  executable:
                    type: string
              args:
                type: array
                items:
                  type: string
              runsOn:
                type: string
                enum:
                - robot
                - cpu
                - gpu
                - any
          status:
            type: object
            properties:
              state:
                type: string
                enum:
                - Running
                - Finished
                - Reallocating
                - FailLoopBackoff
  scope: Namespaced
  names:
    plural: flatboatworkloads
    singular: flatboatworkload
    kind: FlatboatWorkload
    shortNames:
    - wl
    - wls
    - workload
    - workloads
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flatboatbots.flatboat.juancsu.coder
spec:
  group: flatboat.juancsu.coder
  versions:
  - name: v6
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              nodeName:
                type: string
              capabilities:
                type: object
                additionalProperties:
                  type: string
              limitations:
                type: array
                items:
                  type: string
          status:
            type: object
            properties:
              state:
                type: string
                enum:
                - Idle
                - Busy
                - Offline
  scope: Cluster
  names:
    plural: flatboatbots
    singular: flatboatbot
    kind: FlatboatBot
    shortNames:
    - bot
    - bots
