apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flatboatworkloads.flatboat.juancsu.coder
spec:
  group: flatboat.juancsu.coder
  versions:
  - name: v6
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              launch:
                type: object
                properties:
                  package:
                    type: string
                  executable:
                    type: string
              args:
                type: array
                items:
                  type: string
              runsOn:
                type: string
                enum:
                - robot
                - cpu
                - gpu
                - any
  scope: Namespaced
  names:
    plural: flatboatworkloads
    singular: flatboatworkload
    kind: FlatboatWorkload
    shortNames:
    - wl
    - wls
    - fwl
