apiVersion: v1
kind: Namespace
metadata:
  name: flatboat-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flatboat-operator
  namespace: flatboat-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flatboat-operator
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flatboat-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flatboat-operator
subjects:
  - kind: ServiceAccount
    name: flatboat-operator
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flatboat-operator
  namespace: flatboat-operator
spec:
  selector:
    matchLabels:
      app: flatboat-operator
  template:
    metadata:
      labels:
        app: flatboat-operator
    spec:
      serviceAccountName: flatboat-operator
      containers:
        - name: flatboat-operator
          image: juancsucoder/flatboat-operator:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
