apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workloads.flatboat.juancsu.coder
spec:
  group: flatboat.juancsu.coder
  versions:
  - name: v6
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          image:
            type: string
          launch_executable:
            type: string
          args:
            type: array
            items:
              type: string
          runsOn:
            type: string
            enum:
            - robot
            - cpu
            - gpu
            - any
  scope: Namespaced
  names:
    plural: workloads
    singular: workload
    kind: FlatboatWorkload
    shortNames:
    - wl
    - wls
    - fwl
