apiVersion: flatboat.juancsu.coder/v6
kind: FlatboatWorkload
metadata:
  name: example-workload
spec:
  image: osrf/ros:jazzy-desktop-full
  launch:
    package: example_pkg
    executable: example_node
  runsOn: any
  args: []
